        name: Publish Python Package

        on:
          release:
            types: [published]

        jobs:
          publish:
            runs-on: ubuntu-latest
            permissions:
              id-token: write # Required for Trusted Publishers
            steps:
              - uses: actions/checkout@v4
              - name: Set up Python
                uses: actions/setup-python@v5
                with:
                  python-version: '3.x'
              - name: Install build dependencies
                run: python -m pip install --upgrade pip build wheel # Or poetry install if using Poetry
              - name: Build package
                run: python -m build # Or poetry build if using Poetry
              - name: Publish package to PyPI
                uses: pypa/gh-action-pypi-publish@release/v1
                with:
                  # Trusted Publishers configuration
                  repository-url: https://upload.pypi.org/legacy/
